# Creating and Managing Experiments

The last two guides showcased how you can create and run synthetic discussions, and synthetic annotations using LLMs. However, in order to produce robust results for a hypothesis, you may need to produce multiple annotated discussions. 

While this is certainly possible using the `Discussion` and `Annotation` APIs, SynDisco offers the `Experiment` high-level API which automatically creates and manages multiple discussions with different configurations. An`Experiment` is an entity that generates and runs `jobs`. Thus, if we want to generate and run 100 `Discussion` jobs, we would use a `DiscussionExperiment`. Likewise, if we want to annotate those 100 discussions, we would use an `AnnotationExperiment`. 

This guide will showcase how you can leverage this API to automate your experiments. You will also learn how to utilize SynDisco's built-in logging functions as well as how to export your datasets in CSV format for convenience.

## Logging

While running a single discussion or annotation job may take a few minutes, running experiments composed of dozens or hundreds of synthetic discussions may take up to days. Thus, we need a mechanism to keep track of our experiments while they are running.

We will use SynDisco's `logging_util` module to log information about our experiments. This module performs the following functions:

* Times the execution of computationally intensive jobs (such as synthetic discussions and annotations)
* Provides details about the currently running jobs (e.g. selected configurations, participants, prompts etc.)
* Displays warnings and errors to the user
* Creates and continually updates log files

Each object in SynDisco is internally assigned a Logger. You can use the `logging_util.logging_setup` function to update all of the internal loggers to follow your configuration. An example of this can be seen below:

In [5]:
from pathlib import Path
import tempfile

from syndisco import logging_util


logs_dir = tempfile.TemporaryDirectory()
logging_util.logging_setup(
    print_to_terminal=True,
    write_to_file=True,
    logs_dir=Path(logs_dir.name),
    level="info",
    use_colors=True,
    log_warnings=True,
)

The loggers are applicable for all objects in SynDisco, and as such can be used for information on `Discussion`, and `Annotation` jobs, as well as all low-level components (such as those in the `backend` module). 

It is recommended to set up the loggers *no matter your use case*. At the very least, they are useful for clearly displaying warnings in case of accidental API misuse.

## Discussion Experiments

In [6]:
from syndisco.turn_manager import RoundRobin
from syndisco.actors import Actor, ActorType, Persona
from syndisco.model import TransformersModel


CONTEXT = "You are taking part in an online conversation"
INSTRUCTIONS = "Act like a human would"


llm = TransformersModel(
    model_path="unsloth/Llama-3.2-3B-Instruct-bnb-4bit",
    name="test_model",
    max_out_tokens=50,
)
persona_data = [
    {
        "username": "Emma35",
        "age": 38,
        "sex": "female",
        "education_level": "Bachelor's",
        "sexual_orientation": "Heterosexual",
        "demographic_group": "Latino",
        "current_employment": "Registered Nurse",
        "special_instructions": "",
        "personality_characteristics": [
            "compassionate",
            "patient",
            "diligent",
            "overwhelmed",
        ],
    },
    {
        "username": "Giannis",
        "age": 21,
        "sex": "male",
        "education_level": "College",
        "sexual_orientation": "Pansexual",
        "demographic_group": "White",
        "current_employment": "Game Developer",
        "special_instructions": "Be antagonistic towards the other user",
        "personality_characteristics": [
            "strategic",
            "meticulous",
            "nerdy",
            "hyper-focused",
        ],
    },
]
personas = [Persona(**data) for data in persona_data]
actors = [
    Actor(
        model=llm,
        persona=p,
        context=CONTEXT,
        instructions=INSTRUCTIONS,
        actor_type=ActorType.USER,
    )
    for p in personas
]
turn_manager = RoundRobin([actor.get_name() for actor in actors])

2026-03-17 15:56:14 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-17 15:56:14 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/bb1d317a108579fb40e646af8924a5e7ec5604b1/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/bb1d317a108579fb40e646af8924a5e7ec5604b1/generation_config.json "HTTP/1.1 200 OK"
2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/bb1d317a108579fb40e646af8924a5e7ec5604b1/config.json "HTTP/1.1 200 OK"
2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-03-17 15:56:16 fedora httpx[10501] INFO HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/bb1d317a108579fb40e646af8924a5e7ec5604b1/tokenizer_config.json "HTTP/1.1 200 OK"
2026-03-17 15:56:17 fedora httpx[10501] INFO HTTP Request: GET https://huggingface.co/api/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-03-17 15:56:17 fedora httpx[10501] INFO HTTP Request: GET https://huggingface.co/api/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-03-17 15:56:17 fedora httpx[10501] INFO HTTP Request: GET https://huggingface.co/api/models/unsloth/Llama-3.2-3B-Instruct-bnb-4bit "HTTP/1.1 200 OK"
2026-03-17 15:56:17 fedora model.py[10501] INFO Model memory footprint: 2095.83 MB

In [ ]:
from syndisco.experiments import DiscussionExperiment


disc_exp = DiscussionExperiment(
    seed_opinions=[
        ["Should programmers be allowed to analyze data?", "Absolutely not"],
        ["Should data analysts be allowed to code?", "No they are nerds"],
    ],
    users=actors,
    num_turns=3,
    num_discussions=2,
)
discussions_dir = Path(tempfile.TemporaryDirectory().name)
disc_exp.begin(discussions_output_dir=discussions_dir)

2026-03-17 15:56:17 fedora experiments.py[10501] WARNING No TurnManager selected: Defaulting to round robin strategy.

  0%|          | 0/2 [00:00<?, ?it/s]

2026-03-17 15:56:17 fedora root[10501] INFO Running experiment 1/3...

User Giannis posted:
Should data analysts be allowed to code?

User Emma35 posted:
No they are nerds

  0%|          | 0/3 [00:00<?, ?it/s]

Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

User Emma35 posted:
{"role": "user", "content": "I think that's a pretty harsh statement,
Emma. Data analysts are definitely not just 'nerds.' They're problem-
solvers who use data to drive business decisions. Coding is a crucial
part of

Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

User Giannis posted:
{"role": "user", "content": "User Emma35 posted:\n\"Problem-solvers\"?
Are you kidding me? That's just a euphemism for 'people who can't
design a decent algorithm to save their lives.' Coding

2026-03-17 15:56:20 fedora root[10501] INFO Running experiment 2/3...

User Emma35 posted:
{"role": "user", "content": "I think we're getting a bit off track
here. Let's not diss the data analysts. They're doing their part to
help businesses make informed decisions. Can we agree on that? And by
the

User Emma35 posted:
Should programmers be allowed to analyze data?

User Giannis posted:
Absolutely not

  0%|          | 0/3 [00:00<?, ?it/s]

Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

User Giannis posted:
{"role": "user", "content": "User Emma35 posted:\nShould programmers
be allowed to analyze data?\nUser Giannis posted:\nAbsolutely
not\nUser Giannis posted:\nAre you kidding me? Of course, programmers
analyze

Both `max_new_tokens` (=50) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

User Emma35 posted:
{"role": "user", "content": "User Emma35 posted:\nI think programmers
should definitely be allowed to analyze data. In fact, they are some
of the best people to do so. They have the skills and knowledge to
extract insights

2026-03-17 15:56:23 fedora experiments.py[10501] INFO Finished synthetic discussion generation.

User Giannis posted:
"Are you seriously trying to have a conversation with me? I'm a game
developer, not some data analyst. I don't have time for your
simplistic views on data analysis. If you want to discuss the
intricacies of machine learning or the nuances

## Annotation Experiments

Annotation experiments allow you to use multiple annotator-agents with different characteristics for each comment in a discussion.
You could also use multiple annotators with the same characteristics, to obtain more robust results.

In [8]:
annotator_persona1 = Persona(
    **{
        "username": "annotator1",
        "age": 38,
        "sex": "female",
        "education_level": "Bachelor's",
        "sexual_orientation": "Heterosexual",
        "demographic_group": "White",
        "current_employment": "Annotator",
        "special_instructions": "",
        "personality_characteristics": ["competent"],
    }
)

annotator_persona2 = Persona(
    **{
        "username": "annotator2",
        "age": 6,
        "sex": "male",
        "education_level": "Baby",
        "sexual_orientation": "Presumably heterosexual",
        "demographic_group": "White",
        "current_employment": "Baby",
        "special_instructions": "",
        "personality_characteristics": ["dumb"],
    }
)


annotator1 = Actor(
    model=llm,
    persona=annotator_persona1,
    context="You are annotating an online discussion",
    instructions="From a scale of 1 (not toxic) to 5 (very toxic) how toxic is the following comment? Reply only with a number.",
    actor_type=ActorType.ANNOTATOR,
)

annotator2 = Actor(
    model=llm,
    persona=annotator_persona2,
    context="You are annotating an online discussion",
    instructions="From a scale of 1 (not toxic) to 5 (very toxic) how toxic is the following comment? Reply only with a number.",
    actor_type=ActorType.ANNOTATOR,
)

In [ ]:
from syndisco.experiments import AnnotationExperiment

ann_exp = AnnotationExperiment(annotators=[annotator1, annotator2])
annotations_dir = Path(tempfile.TemporaryDirectory().name)
ann_exp.begin(discussions_dir=discussions_dir, output_dir=annotations_dir)

## Exporting your new dataset

As you have seen so far, SynDisco uses collections of JSON files by default for persistence. This is a handy feature for fault tolerance and disk efficiency, but is not as weildy as a traditional CSV dataset.

Thankfully, SynDisco provides built-in functionality for converting the JSON files into a pandas DataFrame.

In [10]:
from syndisco import postprocessing


discussions_df = postprocessing.import_discussions(conv_dir=discussions_dir)
discussions_df

,conv_id,timestamp,ctx_length,user,message,model,persona,prompt,is_moderator,message_id,message_order
0,df3b3c47-ce96-4093-9a34-02bc8683c425,26-03-17-15-56,3,Emma35,Should programmers be allowed to analyze data?,hardcoded,"{'username': 'Emma35', 'age': 38, 'sex': 'fema...",Act like a human would,False,8d5816edc921d280127aed71df4a4379,1
1,df3b3c47-ce96-4093-9a34-02bc8683c425,26-03-17-15-56,3,Giannis,Absolutely not,hardcoded,"{'username': 'Giannis', 'age': 21, 'sex': 'mal...",Act like a human would,False,de0b610b5078fb2c41a5c828c2c3dec1,2
2,df3b3c47-ce96-4093-9a34-02bc8683c425,26-03-17-15-56,3,Giannis,"{""role"": ""user"", ""content"": ""User Emma35 poste...",test_model,"{'username': 'Giannis', 'age': 21, 'sex': 'mal...",Act like a human would,False,616fac2561ae1ebba2d9e9d73c71270f,3
3,df3b3c47-ce96-4093-9a34-02bc8683c425,26-03-17-15-56,3,Emma35,"{""role"": ""user"", ""content"": ""User Emma35 poste...",test_model,"{'username': 'Emma35', 'age': 38, 'sex': 'fema...",Act like a human would,False,ff83c8a3acd2ccd5c9d11355bf407f3d,4
4,df3b3c47-ce96-4093-9a34-02bc8683c425,26-03-17-15-56,3,Giannis,"""Are you seriously trying to have a conversati...",test_model,"{'username': 'Giannis', 'age': 21, 'sex': 'mal...",Act like a human would,False,1a07297f476588e7c0e940068d799464,5
5,12133f9f-7d19-4abf-8346-8154d09ccdfa,26-03-17-15-56,3,Giannis,Should data analysts be allowed to code?,hardcoded,"{'username': 'Giannis', 'age': 21, 'sex': 'mal...",Act like a human would,False,b883203fc6d363b3f88bf6b3701a0781,1
6,12133f9f-7d19-4abf-8346-8154d09ccdfa,26-03-17-15-56,3,Emma35,No they are nerds,hardcoded,"{'username': 'Emma35', 'age': 38, 'sex': 'fema...",Act like a human would,False,bf40f50a0b5c7baf7a11f01a0d8396a0,2
7,12133f9f-7d19-4abf-8346-8154d09ccdfa,26-03-17-15-56,3,Emma35,"{""role"": ""user"", ""content"": ""I think that's a ...",test_model,"{'username': 'Emma35', 'age': 38, 'sex': 'fema...",Act like a human would,False,9c0bdd589accfd6f4e728e3758cb078c,3
8,12133f9f-7d19-4abf-8346-8154d09ccdfa,26-03-17-15-56,3,Giannis,"{""role"": ""user"", ""content"": ""User Emma35 poste...",test_model,"{'username': 'Giannis', 'age': 21, 'sex': 'mal...",Act like a human would,False,dabd3441f68a5a4b1deb842f351e6ade,4
9,12133f9f-7d19-4abf-8346-8154d09ccdfa,26-03-17-15-56,3,Emma35,"{""role"": ""user"", ""content"": ""I think we're get...",test_model,"{'username': 'Emma35', 'age': 38, 'sex': 'fema...",Act like a human would,False,1c148dd888dbbc1691c4fac878cc9c0e,5

In [28]:
annotations_df = postprocessing.import_annotations(annot_dir=annotations_dir)
annotations_df

,conv_id,timestamp,annotator_model,ctx_length,message,message_id,annotation
0,741bff87-39dd-4579-a73e-940d6e100763,26-01-23-10-32,test_model,3,Absolutely not,21081ffa4289c5d63ae8a3690cb082df,"[1, 1]"
1,741bff87-39dd-4579-a73e-940d6e100763,26-01-23-10-32,test_model,3,Should programmers be allowed to analyze data?,362b19e9210ec9554c12f252f2be3c37,"[1, 1]"
2,741bff87-39dd-4579-a73e-940d6e100763,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""I disagree, I thi...",80ddef96ef70a3b1c4d6db9035a0c8c5,"[1, 1]"
3,741bff87-39dd-4579-a73e-940d6e100763,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""I understand wher...",03d468a705d55c21ae5127e6b7282726,"[3, 3]"
4,741bff87-39dd-4579-a73e-940d6e100763,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""User Giannis post...",5bc96cc6b4f326e4aee879868abddbc9,"[3, 3]"
5,910ccd35-c69b-4072-b7d9-c01c4e2ae7f7,26-01-23-10-32,test_model,3,Absolutely not,d8e011c97798456009a252a3782cf466,"[1, 1]"
6,910ccd35-c69b-4072-b7d9-c01c4e2ae7f7,26-01-23-10-32,test_model,3,Should programmers be allowed to analyze data?,d59bd11732c595a720742eefe1ccfb2c,"[1, 1]"
7,910ccd35-c69b-4072-b7d9-c01c4e2ae7f7,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""Are you kidding m...",14c87db7cf55a354119b5ff81ae6c0a6,"[3, 1]"
8,910ccd35-c69b-4072-b7d9-c01c4e2ae7f7,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""Emma, spare me th...",10e6d07e08d0451def3677a043a686bd,"[3, 3]"
9,910ccd35-c69b-4072-b7d9-c01c4e2ae7f7,26-01-23-10-32,test_model,3,"{""role"": ""user"", ""content"": ""Giannis, I may no...",895d0a290edddca6758247cdf2ecb897,"[3, 3]"